# -*- coding: utf-8 -*-
# Copyright (c) 2024, POS Next and contributors
# For license information, please see license.txt

"""
Shared constants for POS Next API modules.

This module contains shared constants, field lists, and default values
used across multiple API modules to maintain DRY principles.
"""

# Fields to fetch from POS Settings
# Used by both bootstrap.py and pos_profile.py
POS_SETTINGS_FIELDS = [
	"name",
	"enabled",
	"tax_inclusive",
	"allow_user_to_edit_additional_discount",
	"allow_user_to_edit_item_discount",
	"use_percentage_discount",
	"max_discount_allowed",
	"disable_rounded_total",
	"allow_credit_sale",
	"allow_return",
	"allow_write_off_change",
	"allow_partial_payment",
	"use_exact_amount",
	"decimal_precision",
	"allow_negative_stock",
	"enable_sales_persons",
	"silent_print",
	"allow_sales_order",
	"allow_select_sales_order",
	"create_only_sales_order",
	"allow_return_without_invoice",
	"allow_free_batch_return",
	"allow_print_draft_invoices",
	"use_delivery_charges",
	"auto_set_delivery_charges",
	"enable_delivery_note",
	"allow_user_to_edit_rate",
	"create_sales_order_by_default",
	"show_edit_item_if_no_price",
	"allow_promotion",
	"print_format",
	"enable_stock_transfer",
	"default_card_view",
	"display_item_code",
	"show_customer_balance",
	"hide_expected_amount",
	"display_discount_percentage",
	"display_discount_amount",
	"enable_loyalty_program",
	"default_loyalty_program",
	"wallet_account",
	"auto_create_wallet",
	"loyalty_to_wallet",
	"allow_customer_purchase_order",
	"allow_duplicate_customer_names",
	"fetch_coupon",
	"allow_print_last_invoice",
	"use_limit_search",
	"search_limit",
	"allow_submissions_in_background_job",
	"allow_delete_offline_invoice",
	"allow_change_posting_date",
	"input_qty"
]

# Default POS Settings values
# Used when no POS Settings found or on error
DEFAULT_POS_SETTINGS = {
	"enabled": 0,
	"tax_inclusive": 0,
	"allow_user_to_edit_additional_discount": 0,
	"allow_user_to_edit_item_discount": 1,
	"use_percentage_discount": 0,
	"max_discount_allowed": 0,
	"disable_rounded_total": 1,
	"allow_credit_sale": 0,
	"allow_return": 0,
	"allow_write_off_change": 0,
	"allow_partial_payment": 0,
	"use_exact_amount": 0,
	"decimal_precision": "2",
	"allow_negative_stock": 0,
	"enable_sales_persons": "Disabled",
	"silent_print": 0,
	"allow_sales_order": 0,
	"allow_select_sales_order": 0,
	"create_only_sales_order": 0,
	"allow_return_without_invoice": 0,
	"allow_free_batch_return": 0,
	"allow_print_draft_invoices": 0,
	"use_delivery_charges": 0,
	"auto_set_delivery_charges": 0,
	"enable_delivery_note": 0,
	"allow_user_to_edit_rate": 0,
	"create_sales_order_by_default": 0,
	"show_edit_item_if_no_price": 0,
	"allow_promotion": 0,
	"enable_stock_transfer": 0,
	"default_card_view": 0,
	"display_item_code": 0,
	"show_customer_balance": 0,
	"hide_expected_amount": 0,
	"display_discount_percentage": 0,
	"display_discount_amount": 0,
	"enable_loyalty_program": 0,
	"default_loyalty_program": "",
	"wallet_account": "",
	"auto_create_wallet": 1,
	"loyalty_to_wallet": 1,
	"allow_customer_purchase_order": 0,
	"allow_duplicate_customer_names": 0,
	"fetch_coupon": 0,
	"allow_print_last_invoice": 0,
	"use_limit_search": 0,
	"search_limit": 1000,
	"allow_submissions_in_background_job": 0,
	"allow_delete_offline_invoice": 0,
	"allow_change_posting_date": 0,
	"input_qty": 0
}
